language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
env:
    - SUPERVISOR_PYTHON_VERSION=2.7
install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - ./install_supervisor
script:
    - .githooks/pre-commit -f
    - python -m unittest discover
sudo: false
